# Generated by Django 4.2.7 on 2023-11-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_aricle_image_alter_aricle_title_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aricle',
            new_name='Article',
        ),
    ]
